[project]
name = "docketbird-mcp"  
version = "0.1.0"
dependencies = [
    "mcp>=1.2.0",
    "requests>=2.31.0", 
    "python-dotenv>=1.0.0",
    "fastapi",
    "uvicorn",
    "pydantic",
    "termcolor"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
